### ISSUE TITLE
Upgrade to Spark 3.0

### ISSUE THREAD

**Issue by xandrew-lynx** [lynxkite/lynxkite#66]
It seems despite the new major version, "No major code changes are required to adopt this version of Apache Spark."

It seems to have quite a few improvements. It would also allow for GPU acceleration as point out by Gyorgy Mezo.

**Comment by darabos** [comment]
It will be a lot of work because their release build is now for Scala 2.12 which is also running on Java 11+ I think. Which means we will have to upgrade or ditch a lot of dependencies that don't have Scala 2.12 builds for the versions that we use.

But we should definitely do it! LynxKite 4.1? Let's try.

**Comment by darabos** [comment]
I'll start on this after #11 is in.

**Comment by darabos** [comment]
I'm doing this for real now. With Spark 3 we are also upgrading to Scala 2.12 finally. But https://github.com/vegas-viz/Vegas does not exist for Scala 2.12. It's the worst part of LynxKite anyway, so I'm inclined to remove it. Is there a way we could do that without breaking much compatibility?

Vegas just builds the JSON for Vega-lite anyway. It's a better for everyone if the user has to specify the JSON directly instead of through this weird Scala API.

Three ideas for compatibility:
- Add a tool to LynxKite that lets you switch to JSON. Do this in LynxKite 4.2.1. Then you can upgrade to 4.2.1 and switch the Scala code to JSON before upgrading to 4.3.0. 4.3.0 will no longer include Vegas.
- Write a compatibility layer that covers most of Vegas. I've only ever used 1-2 functions from it.
- Assume there are very few LynxKite users who ever figured out this API. Just write a migration guide and apologize for the inconvenience.

I'm leaning to the last one actually. I really don't believe there is a large amount of work sunk into creating elaborate Vegas charts out there.

**Comment by xandrew-lynx** [comment]
Agreed with the last option. We have some built in custom boxes we need to convert (or remove?) ourselves. If we convert we can include those as example in the migration guide. Also, one small thing that could help is if the new Vega lite box gives a nice error message with a link to the migration guide if it detects that its input is not json.

**Comment by darabos** [comment]
Done in #178.
